title: "feiyang.log"
description: "small notes, quiet jokes, and unresolved states"
author: "Feiyang 飞扬"
logo: "/assets/img/site-thumbnail.png"

markdown: kramdown
highlighter: rouge
permalink: /:title.html
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
