source "https://rubygems.org"

gem "jekyll", "~> 4.2.2"
gem "jekyll-feed", "~> 0.17"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-sass-converter", "~> 2.2"
gem "ffi", "1.15.5"
gem "csv"
gem "base64"
gem "bigdecimal"
